[package]
name = "subauth"
version = "0.1.0"
edition = "2024"
authors = ["Stipulations"]


[dependencies]
axum = "0.8.4"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.41"
serde = { version = "1.0", features = ["derive"] }
sysinfo = "0.36.0"